version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi_app

  fastapi_app:
    container_name: fastapi_app
    build: .
    expose:
      - "80"
    depends_on:
      - mysql
#     - redis

  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - ./.mysqlenv
    ports:
      - "3306:3306"

# redis:
#   container_name: redis
#   image: "redis:alpine"
#   ports:
#     - "6379:6379"
